name: brm
description: Biblical Relationship Management - An evangelism tracking application
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.4"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  flutter_modular: ^6.3.4
  drift: ^2.22.1
  sqlite3_flutter_libs: ^0.5.26
  path_provider: ^2.1.5
  path: ^1.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  excel: ^4.0.6
  file_picker: ^8.1.4
  intl: ^0.19.0
  flutter_local_notifications: ^18.0.1
  equatable: ^2.0.7
  dartz: ^0.10.1
  sqlite3: ^2.5.0
  flutter_screen_controller: ^0.0.5+1
  url_launcher: ^6.3.1
  table_calendar: ^3.1.2
  local_auth: ^2.3.0
  syncfusion_flutter_charts: ^27.2.5
  fl_chart: ^0.69.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  drift_dev: ^2.22.0

flutter:
  uses-material-design: true
